#8.15.21 and 9.16.21
#minor revisions 6.11.23
def dateformat(unixtime):
    timestamp = datetime.datetime.fromtimestamp(unixtime)
    fdate = timestamp.strftime("a%m.%e.%yx%I:%M %p")
    fdate = fdate.replace('a0', '')
    fdate = fdate.replace('x0', ' ')
    fdate = fdate.replace('. ', '.')
    fdate = fdate.replace('a', '')
    fdate = fdate.replace('x', ' ')
    fdate = fdate.replace('AM', 'am')
    fdate = fdate.replace('PM', 'pm')
    ftime = timestamp.strftime("%H%M")
    isodate = timestamp.strftime("%Y%m%d%H%M")
    return ftime, fdate, isodate
import os
import datetime
search_dir = "notes/"
notes = os.listdir(search_dir)
badNames=[".DS_Store"]
for i in notes:
    if i in badNames:
        notes.remove(i)
names = []
dates = []
times = []
sizes = []
isodates = []
pretable = """
<!DOCTYPE html>
<!--Generated by sorting-notes (https://github.com/jmoll1125/sorting-notes/)-->
<html>
<head>
<title>the notes folder</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
td { padding: 0px; padding-right: 5px; border-bottom: 15px;}
a { text-decoration: none; }
a:visited{color:blue}
.red {color: rgb(199, 97, 90); }
thead {display: none;}
.hidden {display: none;}
</style>
<script src="sorttable.js"></script>
<script>
function sort(id) {
var myTH = document.getElementsByTagName("th")[id];
sorttable.innerSortFunction.apply(myTH, []);
};
</script>
</head>
<body>
<h1>the notes folder</h1>
<p>sort by: <a href="#" onclick="sort(1)">name</a> &nbsp; <a href="#" onclick="sort(0)">date</a> &nbsp; <a href="#" onclick="sort(2)">time</a> &nbsp; <a href="#" onclick="sort(3)">size</a>
<table id="notes" class="sortable">
<thead><tr><th>date</th><th>name</th><th>time</th><th>size</th></thead>
<tbody>
"""
posttable = """
</tbody>
</table>

</body>
</html>
"""
html = ""
for x in range (0, len(notes)):
    sizes.append(os.path.getsize(search_dir+notes[x]))
    utime = os.path.getmtime(search_dir+notes[x])
    ts = dateformat(utime)
    times.append(ts[0])
    dates.append(ts[1])
    isodates.append(ts[2])
    names.append(notes[x])
    #html = html + "<a href=\"" + names[x] +"\">" + dates[x] + "&nbsp;&nbsp;" + names[x] +"</a><br>"
    #if there's no name we'll just make the date the link
    html = html + "<tr><td sorttable_customkey=\"" + isodates[x] + "\">" + dates[x] + "</td><td><a href=\"" + search_dir + names[x] +"\">" + names[x] +"</a></td><td class=\"hidden\">" + times[x] + "</td><td class=\"hidden\">" + str(sizes[x]) + "</td></tr>\r\n"
filename = datetime.datetime.now()
filename = filename.strftime("%Y%m%d%H%M")
filename = "new file " + filename + ".html"
f = open(filename, "w")
f.write(pretable)
f.write(html)
f.write(posttable)
f.close()
